POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFudHRpcG9pa2EiLCJpZCI6IjYyYTVkZDU2NjBkMWJkNWFhMWJhNTVjZSIsImlhdCI6MTY1NTEwNzE2NX0.8r740RsvyXxKzCe5c1_rJuozKW4YzN4wE6dimkxf0Jk

{
  "title": "ja taaas kävi näin",
  "author": "Matti Kukkarossa",
  "url": "www.wtf.fi",
  "likes": 345
}